SET SQL_LOG_BIN=0;

GRANT ALL PRIVILEGES ON *.* TO root@'localhost' IDENTIFIED BY 'Passw0rd!' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO root@'127.0.0.1' IDENTIFIED BY 'Passw0rd!' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO root@'%' IDENTIFIED BY 'Passw0rd!' WITH GRANT OPTION;

CREATE USER rpl_user@'%' IDENTIFIED BY  'Passw0rd!';
GRANT REPLICATION SLAVE ON *.* TO rpl_user@'%';

FLUSH PRIVILEGES;

SET SQL_LOG_BIN=1;

CHANGE MASTER TO MASTER_USER='rpl_user', MASTER_PASSWORD='Passw0rd!' FOR CHANNEL 'group_replication_recovery'; 

INSTALL PLUGIN group_replication SONAME 'group_replication.so'

